package com.yk.tripinfo.app

object AppConfig {
    val runningQOrLater = android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.Q
    const val REQUEST_FOREGROUND_AND_BACKGROUND_PERMISSION_RESULT_CODE = 33
    const val REQUEST_FOREGROUND_ONLY_PERMISSIONS_REQUEST_CODE = 34
    const val REQUEST_TURN_DEVICE_LOCATION_ON = 29
    const val LOCATION_PERMISSION_INDEX = 0
    const val BACKGROUND_LOCATION_PERMISSION_INDEX = 1
    const val REQUESTING_LOCATION_UPDATES_KEY = "REQUESTING_LOCATION_UPDATES_KEY"

    const val ACTION_PROCESS_LOCATION_UPDATES = "com.yk.tripinfo.action.PROCESS_LOCATION_UPDATES"

    const val FASTEST_UPDATE_INTERVAL = 1000 * 60 * 15L
    const val FORE_GROUND_UPDATE_INTERVAL = 1000 * 60 * 1
    const val MAX_WAIT_TIME = FORE_GROUND_UPDATE_INTERVAL * 3

}